version: "3.1"

services:
  db:
    build:
      context: ./
      dockerfile: db.dockerfile
    ports:
      - 5432:5432

  db-wait:
    image: jwilder/dockerize
    command: dockerize -wait tcp://db:5432 -timeout 1m
    depends_on:
      - db
